<?php

namespace App\Http\Controllers\Auth;

use App\Actions\Fortify\PasswordValidationRules;
use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Inertia\Inertia;
use Inertia\Response;

/**
 * Phase 5 sub-step 4: guest-only acceptance of a signed admin invitation. The email/role are
 * carried entirely in the signed URL (`URL::temporarySignedRoute`, generated by
 * `UserController::invite()`) — there's no separate `invitations` table, so nothing to clean up
 * and no server-side state that could go stale. The route's own `signed` middleware rejects a
 * tampered or expired link before this controller ever runs; `unique:users,email` in `store()`
 * additionally guarantees the link can't be "accepted" twice.
 */
class InviteAcceptController extends Controller
{
    use PasswordValidationRules;

    public function show(Request $request): Response
    {
        return Inertia::render('Auth/AcceptInvite', [
            'email' => $request->query('email'),
            'role' => $request->query('role'),
        ]);
    }

    public function store(Request $request): RedirectResponse
    {
        // Trust `email`/`role` from the SIGNED query string, never from the POST body — the
        // signature is what proves these two values weren't tampered with since the invite was
        // created; a client-submitted `email`/`role` field would have no such guarantee.
        $email = (string) $request->query('email');
        $role = (string) $request->query('role');

        $data = Validator::make($request->all() + ['email' => $email, 'role' => $role], [
            'email' => ['required', 'email'],
            'role' => ['required', 'string'],
            'name' => ['required', 'string', 'max:255'],
            'password' => $this->passwordRules(),
        ])->validate();

        // The route's own `signed` middleware already verified `email`/`role`/`expires` weren't
        // tampered with — re-checking `unique` here closes the only remaining race (two people
        // submitting the same still-valid link at once).
        if (User::where('email', $data['email'])->exists()) {
            return redirect()->route('login')->withErrors([
                'email' => 'This invitation has already been used. Please log in instead.',
            ]);
        }

        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);
        // `email_verified_at` isn't in User::$fillable (deliberately), so it's set via forceFill
        // rather than the mass-assignable create() call.
        $user->forceFill(['email_verified_at' => now()])->save(); // came through a signed invite link — trust the email
        $user->assignRole($data['role']);

        Auth::login($user);
        $request->session()->regenerate();

        return redirect()->route('admin.dashboard');
    }
}
