<?php

namespace App\Support;

use App\Models\GalleryImage;
use App\Services\SecureUploadService;
use Illuminate\Support\Facades\Storage;

/**
 * Resolves the images for the homepage bridal slider, in strict precedence:
 *
 *   1. Gallery images an admin has ticked "Show on Homepage Slider" (in an active album).
 *   2. Failing that, whatever real images sit in `public/images/` (see PublicImageScanner).
 *
 * The fallback exists so the homepage is never left with an empty slider on a fresh install or
 * before anyone has curated the gallery — but it is genuinely a FALLBACK, not a blend. Mixing the
 * two would mean an admin who ticks one photo suddenly sees it alongside four unrelated files from
 * the filesystem, and un-ticking their last selection would look like the toggle had broken.
 *
 * Ordering uses the album's `sort` then the image's own `sort`, which is what the existing admin
 * reorder arrows already write — so "re-order slider priority" needed no second ordering column or
 * second set of controls. See the `show_on_homepage` migration for why.
 */
class FeaturedGalleryImages
{
    /**
     * @return list<array{id: int|string, url: string, webp_url: string|null, alt: string, source: string}>
     */
    public static function resolve(): array
    {
        $curated = GalleryImage::query()
            ->forHomepageSlider()
            ->with('gallery:id,title,sort,is_active')
            ->get()
            // Sorted in PHP rather than SQL: the album's `sort` lives on the related table, and a
            // sortBy over at most a handful of curated rows is cheaper to read than a join here.
            //
            // A single zero-padded composite key rather than `sortBy([fn, fn])` — that array form
            // expects [attribute, direction] pairs, NOT bare closures, and silently produced an
            // arbitrary order (caught by checking the real output, which came back 4-2-3-1).
            // Padding keeps the comparison numeric-by-position, so album 2 image 10 still sorts
            // after album 2 image 9 rather than lexicographically before it.
            ->sortBy(fn (GalleryImage $image) => sprintf(
                '%010d:%010d:%010d',
                $image->gallery?->sort ?? 0,
                $image->sort,
                $image->id,
            ))
            ->values();

        if ($curated->isNotEmpty()) {
            return $curated
                ->map(fn (GalleryImage $image) => [
                    'id' => $image->id,
                    'url' => asset("storage/{$image->image_path}"),
                    // Uploads get a .webp sibling generated by SecureUploadService; serve it when
                    // it really exists on disk rather than assuming the convention held.
                    'webp_url' => self::webpUrl($image->image_path),
                    // Falls back to the album title so a caption-less photo still gets meaningful
                    // alt text instead of an empty string a screen reader would skip.
                    'alt' => $image->caption ?: ($image->gallery?->title ?? 'Bridal photograph'),
                    'source' => 'gallery',
                ])
                ->all();
        }

        return array_map(
            fn (array $image) => [...$image, 'webp_url' => null],
            PublicImageScanner::bridalFallback(),
        );
    }

    private static function webpUrl(?string $path): ?string
    {
        if (! $path) {
            return null;
        }

        $webpPath = SecureUploadService::webpSiblingPath($path);

        return Storage::disk('public')->exists($webpPath) ? asset("storage/{$webpPath}") : null;
    }
}
